### DISCUSSION TITLE
Cache missed in Bitbucket

### DISCUSSION THREAD

**Discussion by jonathansayag** [vercel/turborepo#10243] [Help]
### Summary

Hi,

I am trying to implement turbo in the CI of my Bitbucket repository.

Using the Bitbucket pipeline cache system, i'am caching after each pipeline the folder `.turbo` which contains the `cache` folder + `runs` folder.

Actually, each time i run the Bitbucket pipeline : 

1. the `.turbo` folder cached previously is retrieved & downloaded to the bitbucket repository build folder
2. i ensure to have the `.turbo`  cached folder during the build  by using `ls -la` 
3. i run the pnpm turbo lint command
4. Then, for each lint task i have `@package/utils:lint: cache miss, executing ***************`
5. To check what is going on & what Bitbucket is caching, i put `./turbo/**` into an artifact that Bitbucket will generate
6. I download the artifact & check all the files
7. And here is the headache : when i lookup for a task ID from the file `.turbo/runs/****.json` in the folder `.turbo/cache`, i have the the cache tar.gz ! For example, for the task ID `4ec1005ee17a6124` from the `.turbo/runs/****.json`, there is a `.turbo/cache/4ec1005ee17a6124.tar.zst`.

And each time i re-run the Bitbucket pipeline, each time it has the same cache but turbo does not hit it.

### Example

My `turbo.json` :

```
{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {},
    "lint": {
      "dependsOn": ["^lint"]
    }
  }
}
```

My `bitbucket-pipelines` :

```
image: node:20.15.1
definitions:
  caches:
    global-node: /usr/local/lib/node_modules
    turbo: .turbo
    pnpm: .pnpm-store
pipelines:
  custom:
    lint-with-turbo:
      - step:
          name: Run lint
          caches:
            - global-node
            - turbo
            - pnpm
          clone:
            lfs: true
          size: 8x
          script:
            - corepack enable && corepack prepare pnpm@9.5.0 --activate
            - pnpm install
            - ls -la .turbo
            - pnpm turbo lint --summarize
          artifacts:
            - .turbo/**
```

Can you help me ?
