### DISCUSSION TITLE
Turborepo LFS fetch

### DISCUSSION THREAD

**Discussion by jakeleventhal** [vercel/turborepo#10446] [Ideas]
### Goals

Create a turbo command to intelligently fetch all LFS files that are needed by a turbo project

### Background

I have a large monorepo with 12 next apps deploying to Vercel. In my GitHub actions deployment, I am triggering a job for each app to deploy. My monorepo has a number of LFS files (images/videos/etc.).

These files are mostly used by 2-3 of my apps and the other apps don't use LFS files at all. I am accruing a large git LFS bill due to downloading all my LFS files over and over.

### Proposal

Implement a turbo command that interfaces with git to find all dependent LFS files needed for a specific turbo script. For example assume I have a turbo script for `deploy` and an app called `@myrepo/app1`. I can fetch my repo without LFS files, then use this command to fetch only the files I need from git lfs with something like this:
```bash
turbo fetch-lfs deploy -F @myrepo/app1
```
Under the hood this command basically creates a set intersection of all git lfs files and the file dependencies of my turbo task, then uses git lfs to fetch only that intersecting set.

Here is an example of the under the hood logic that seems to grab the correct files as a workaround:
```bash
comm -12 \
  <(git lfs ls-files -n | xargs -n1 basename | sort) \
  <(turbo run deploy -F @myrepo/app1 --dry=json | jq -r '.tasks[].inputs | keys[]' | xargs -n1 basename | sort)
```

**Comment by anthonyshew** [comment]
Have you tried using `git checkout <branch> --filter=blob:none --depth=0`? This will lazily fetch whatever files are requested within history. I'm not sure what this does for LFS files, but it might be the right place to start.

On the Turborepo side, I don't see this being in our scope.

**Reply by jakeleventhal** [reply]
@anthonyshew I kind of disagree here. Perhaps LFS specifically is out of scope of for turbo, but the only way we can get affected turbo files is a bit hacky.

We ended up creating this `action.yaml` file:
```yaml
name: Download LFS Files
description: Download LFS files for a specific package deployment.

inputs:
  package:
    description: The name of the package to deploy.
    required: true

runs:
  using: composite
  steps:
    - name: Download necessary LFS files
      shell: bash
      run: |
        # Get list of full LFS-tracked file paths
        lfsFiles=$(git lfs ls-files -n | xargs -n1 basename | sort)

        # Get all files needed by the package
        neededFiles=$(npx turbo run deploy:${{ env.VERCEL_ENV }} -F ${{ inputs.package }}... --dry=json \
          | jq -r '.tasks[].inputs | keys[]' | xargs -n1 basename | sort)

        # Find intersection of LFS files and needed files
        matchedLfsFiles=$(comm -12 <(echo "$lfsFiles") <(echo "$neededFiles"))

        if [ -z "$matchedLfsFiles" ]; then
          echo "No LFS files to download. Skipping 'git lfs pull'."
        else
          echo "::group::LFS files to download"
          echo "$matchedLfsFiles"
          echo "::endgroup::"

          git lfs pull --include="$(echo "$matchedLfsFiles" | paste -sd, -)"
        fi
```

I think at the very least having a cleaner way to get affected files is something that turbo could own. This part:
```bash
# Get all files needed by the package
neededFiles=$(npx turbo run deploy:${{ env.VERCEL_ENV }} -F ${{ inputs.package }}... --dry=json \
  | jq -r '.tasks[].inputs | keys[]' | xargs -n1 basename | sort)
```
This could easily be a turbo command instead of having to hack/parse json. We could have a command like:
```bash
turbo ls-files deploy -F @myrepo/app1...
```
That would be a much cleaner solution.
