### DISCUSSION TITLE
Running tests on Github Actions

### DISCUSSION THREAD

**Discussion by lkedmi** [vercel/turborepo#1352] [Help] [answered]
I might be totally missing the point here, I could use some help!

I have a Turborepo project with 3 apps where every app has its own environment variables and tests.

I'm trying to setup a Github Actions workflow to run the tests whenever a new commit is pushed to remote but I'm not sure how to provide each app the relevant environment variables.

When running in `dev` mode, environment variables are pulled using doppler; when running in `production` mode, environment variables are pulled directly from Vercel. The missing piece is where to pull the environment variables when running in `test` mode.

Here's my current workflow (which fails on build due to missing environment variables):
```yaml
name: CI

on:
  push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install MYSQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{ secrets.MYSQL_DATABASE }}
          mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build:test

      - name: Start
        run: yarn start:test

      - name: Run tests
        run: yarn test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

Would appreciate your help figuring this out!
