### DISCUSSION TITLE
Need help with failed job using pnpm + Github Actions

### DISCUSSION THREAD

**Discussion by coreybruyere** [vercel/turborepo#3751] [Help] [answered]
First time using pnpm after cloning and creating a private design system repo. I'm looking to setup Actions in Github and am encountering this error:

```
@[MYORG]-core:build: ERROR: command finished with error: exec: "pnpm": executable file not found in $PATH
```

How do I add pnpm to my $PATH within my release.yml file?

File looks like this:
```


name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
        ```
