### DISCUSSION TITLE
Action job failing on "Create Release Pull Request or Publish to npm"

### DISCUSSION THREAD

**Discussion by coreybruyere** [vercel/turborepo#3786] [Help]
I've cloned the design systems turborepo and am running in errors when trying to publish following turborepo [design system docs](https://vercel.com/templates/react/turborepo-design-system). Here's the error:


```
Run changesets/action@v1
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
/usr/bin/git checkout changeset-release/main
error: pathspec 'changeset-release/main' did not match any file(s) known to git
/usr/bin/git checkout -b changeset-release/main
Switched to a new branch 'changeset-release/main'
/usr/bin/git reset --hard 0fd01b1a0f942377f183e25c9ed200d0a8aa7d04
HEAD is now at 0fd01b1 Merge pull request #2 from designInc/0.0.1Release
/opt/hostedtoolcache/node/16.19.0/x64/bin/node /home/runner/work/design-design-system/design-design-system/node_modules/.pnpm/@changesets+cli@2.26.0/node_modules/@changesets/cli/bin.js version
🦋  All files have been updated. Review them and commit at your leisure
/usr/bin/git status --porcelain
 D .changeset/serious-items-approve.md
 M apps/docs/package.json
 M packages/design-core/package.json
 M packages/design-tsconfig/package.json
?? packages/design-core/CHANGELOG.md
?? packages/design-tsconfig/CHANGELOG.md
/usr/bin/git add .
/usr/bin/git commit -m Version Packages
[changeset-release/main c5c2b12] Version Packages
 6 files changed, 18 insertions(+), 10 deletions(-)
 delete mode 100644 .changeset/serious-items-approve.md
 create mode 100644 packages/design-core/CHANGELOG.md
 create mode 100644 packages/design-tsconfig/CHANGELOG.md
/usr/bin/git push origin HEAD:changeset-release/main --force
/home/runner/work/_actions/changesets/action/v1/dist/index.js:192
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.request=void 0;var e=require("@octokit/endpoint"),t=require("universal-user-agent"),r=require("is-plain-object"),s=o(require("node-fetch")),n=require("@octokit/request-error");function o(e){return e&&e.__esModule?e:{default:e}}const u="5.6.3";function i(e){return e.arrayBuffer()}function a(e){const t=e.request&&e.request.log?e.request.log:console;((0,r.isPlainObject)(e.body)||Array.isArray(e.body))&&(e.body=JSON.stringify(e.body));let o,u,i={};return(e.request&&e.request.fetch||s.default)(e.url,Object.assign({method:e.method,body:e.body,headers:e.headers,redirect:e.redirect},e.request)).then(async r=>{u=r.url,o=r.status;for(const e of r.headers)i[e[0]]=e[1];if("deprecation"in i){const r=i.link&&i.link.match(/<([^>]+)>; rel="deprecation"/),s=r&&r.pop();t.warn(`[@octokit/request] "${e.method} ${e.url}" is deprecated. It is scheduled to be removed on ${i.sunset}${s?`. See ${s}`:""}`)}if(204!==o&&205!==o){if("HEAD"===e.method){if(o<400)return;throw new n.RequestError(r.statusText,o,{response:{url:u,status:o,headers:i,data:void 0},request:e})}if(304===o)throw new n.RequestError("Not modified",o,{response:{url:u,status:o,headers:i,data:await d(r)},request:e});if(o>=400){const t=await d(r);throw new n.RequestError(c(t),o,{response:{url:u,status:o,headers:i,data:t},request:e})}return d(r)}}).then(e=>({status:o,url:u,headers:i,data:e})).catch(t=>{if(t instanceof n.RequestError)throw t;throw new n.RequestError(t.message,500,{request:e})})}async function d(e){const t=e.headers.get("content-type");return/application\/json/.test(t)?e.json():!t||/^text\/|charset=utf-8$/.test(t)?e.text():i(e)}function c(e){return"string"==typeof e?e:"message"in e?Array.isArray(e.errors)?`${e.message}: ${e.errors.map(JSON.stringify).join(", ")}`:e.message:`Unknown error: ${JSON.stringify(e)}`}function f(e,t){const r=e.defaults(t);return Object.assign(function(e,t){const s=r.merge(e,t);if(!s.request||!s.request.hook)return a(r.parse(s));const n=(e,t)=>a(r.parse(r.merge(e,t)));return Object.assign(n,{endpoint:r,defaults:f.bind(null,r)}),s.request.hook(n,s)},{endpoint:r,defaults:f.bind(null,r)})}const l=f(e.endpoint,{headers:{"user-agent":`octokit-request.js/5.6.3 ${(0,t.getUserAgent)()}`}});exports.request=l;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

a [HttpError]: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}
    at /home/runner/work/_actions/changesets/action/v1/dist/index.js:192:1285
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 422,
  response: {
    url: 'https://api.github.com/search/issues?q=repo%3AdesignInc%2Fdesign-design-system+state%3Aopen+head%3Achangeset-release%2Fmain+base%3Amain+is%3Apull-request',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'cache-control': 'no-cache',
      connection: 'close',
      'content-length': '301',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 13 Feb 2023 21:37:57 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '3380:7B37:52A9621:AA4DD11:63EAADB5',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '29',
      'x-ratelimit-reset': '1676324337',
      'x-ratelimit-resource': 'search',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [
        {
          message: 'The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.',
          resource: 'Search',
          field: 'q',
          code: 'invalid'
        }
      ],
      documentation_url: 'https://docs.github.com/v3/search/'
    }
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/search/issues?q=repo%3AdesignInc%2Fdesign-design-system+state%3Aopen+head%3Achangeset-release%2Fmain+base%3Amain+is%3Apull-request',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {
          'api.github.com:443:::::::::::::::::::::': [ [TLSSocket] ]
        },
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:443:::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:443:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound r]
    }
  }
}
```
Here is my release.yml

```
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
```
