### DISCUSSION TITLE
Docusaurus deployment ?

### DISCUSSION THREAD

**Discussion by jy95** [vercel/turborepo#4079] [Help] [answered]
Hello,

I would like to add a preview feature to this [repo](https://github.com/jy95/docusaurus-json-schema-plugin) whose deployment of the Docusaurus website on Github Pages is done following these steps : 

```yml
name: Documentation

on:
  push:
    paths:
      - '.github/workflows/documentation.yml'
      - 'testsite/**'
      - 'src/**'
  repository_dispatch:
    types: [generate-documentation]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "lts/*"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3.2.4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-testsite-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-testsite-
      - name: Install lib 💻
        run: |
          npm install
      - name: Build lib 🤖
        run: |
          npm run build
      - name: Link lib 🔗
        run: |
          npm link
      - name: Install website 💻
        run: |
          cd testsite   
          npm link docusaurus-json-schema-plugin --save     
          npm install --prefer-dedupe  
          npm dedupe  
      - name: Build website 🤖
        run: |
          cd testsite   
          yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./testsite/build
```

So I read some pages : 
- https://turbo.build/repo/docs/ci/github-actions
- https://turbo.build/repo/docs/handbook/sharing-code
- ...

But I couldn't find the proper way to achieve it

Thanks in advance,
