### DISCUSSION TITLE
Cache always missed (with Gitlab CI)

### DISCUSSION THREAD

**Discussion by ryanerringtonbd** [vercel/turborepo#4381] [Help]
I am trying to enable remote caching for my project which builds with Gitlab CI/CD. I can see `Remote caching enabled` in the logs but every run outputs `cache miss` & `Cached:    0 cached, 1 total`.

I have followed the steps on the CI Recipes page for Gitlab: https://turbo.build/repo/docs/ci/gitlabci

`.gitlab-ci.yaml` file is configured as follows:

```
.pnpm:
  variables:
    TURBO_TOKEN: $TURBO_TOKEN
    TURBO_TEAM: $TURBO_TEAM
  before_script:
    - cd frontend
    - corepack enable
    - corepack prepare pnpm@latest-7 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - frontend/pnpm-lock.yaml
    paths:
      - frontend/.pnpm-store

build-frontend:
  extends: .pnpm
  image: node:18-alpine
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
```

Is anything missing here? How can I debug this?
