### DISCUSSION TITLE
only re-run the failed step

### DISCUSSION THREAD

**Discussion by haquezameer** [vercel/turborepo#4396] [Help]
I have this workflow which runs on PR

```
name: Validate PR

on:
  pull_request:
    branches:
      - main
      - dev
      - release

  workflow_dispatch:

jobs:
  build-test-validate:
    timeout-minutes: 30
    runs-on: [self-hosted, staging]
    steps:
      - name: change permission before checkout
        run: sudo chown -R $USER:$USER /home/ec2-user/actions-runner/_work/my_project
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Cache turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Validate
        run: yarn pre:validate && yarn validate
      - name: Test
        run: yarn test:ci
```

My project has some flaky tests due to which the `yarn test:ci` often fails. Due to this the `cache` is not stored by `actions/cache`and hence if I re-run failed job all the tasks re-run.

How can I only have the failed task re-run? Should I split the test into a separate job?
