### DISCUSSION TITLE
filter [origin/main] not working in github actions

### DISCUSSION THREAD

**Discussion by AndyOooh** [vercel/turborepo#4594] [Help]
Hi,

I'm trying to set up a CI pipeline which lints and builds any workspaces which have changes compared to the current remote main branch. For that I'm using --filter=[origin/main] as I have seen other people do. It works fine when I run it locally in my terminal but when I run it on github the remote branch is not found. This is my script:

EDIT for context:
main branch is protected with PR required, so this workflow triggers on all other branches. The flow is: branch out from main, commit changes and push to dedicated remote feature branch, the PR to main. This script is triggered on push to new remote feature branch.

```
name: Push to any
run-name: Build on push to any branch except main

on:
  push:
    branches-ignore:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Install Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install TurboRepo CLI
        run: yarn global add turbo
      - name: Lint, Build, and Test
        run: |
          yarn
          turbo run lint --filter="...[origin/main]"
          # turbo build
          # turbo test (not implemented yet)

```

The error I'm getting:
_ERROR  run failed: failed to resolve packages to run: git error: revspec 'origin/main' not found; class=Reference (4); code=NotFound (-3)_

I have tried several variations, e.g. --filter="...[origin/main]", --filter=[origin/main] etc.

What am I misssing?
