### DISCUSSION TITLE
Deploying on Google Cloud Run with Github Actions

### DISCUSSION THREAD

**Discussion by atulmy** [vercel/turborepo#4628] [Help]
I'm unable to wrap head around setting up CI/CD via Github actions for following turbo example
https://github.com/vercel/turbo/tree/main/examples/with-docker

Considering each app will have its own Dockerfile, how to trigger and deploy on Google Cloud Run for example with following `.github/workflows/api.yml` file:

```
name: CI/CD

on:
  push:
    branches: [main]
    paths:
      'apps/api/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: us-west1
  SERVICE_NAME: monorepo-api
  PORT: 3001

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: Setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --timeout=1200s

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$GCP_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated \
            --port=$PORT
```
