### DISCUSSION TITLE
Help deploying turbo repo to vercel using github action

### DISCUSSION THREAD

**Discussion by chukwumaijem** [vercel/turborepo#5815] [Help]
Hi, I had a simple nextjs project that was deployed to Vercel using GitHub action. All worked well until the app was refactored to use Turborepo. Now the app is broken on Vercel.

From error about missing `styled-jsx/package.json`(I'm not using `styled-jsx` in the project) to cannot find module `client-only`

I suspect this has to do with the way turbo-repo packages are installed and linked. Perhaps vercel build is missing some packages in the build output. Here is my github action. Any help will be appreciated.

```yml
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - develop

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest && vercel link --repo --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: cd apps/web && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: cd apps/web && vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: cd apps/web && vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} 
```
