### DISCUSSION TITLE
Cache .cache folder with Azure Pipeline

### DISCUSSION THREAD

**Discussion by florianmatz** [vercel/turborepo#750] [Help] [answered]
The question is not necessarily concern turborepo, but does someone have a example how to preserve the cache folder within node_modules/.cache?

When running a azure pipeline on different agents node_modules is always generated new, in conclusion also turborepos cache, so one of the main advantages of building/testing/linting only affected apps/packages can’t be achieved.

There are several examples / docs from Microsoft how to cache the complete node_modules folder or some other pipeline artifacts.

Has someone a working example/idea?

I’d also whished turborepos docs would be a bit more verbose about integrating into existing CI/CD environments and not only how to implement a custom remote cache, which is nice for local.

**Comment by weyert** [comment, marked as answer]
My understanding is that the default behaviour is to store the cache `node_modules/.cache/turbo`. Alternatively, what you could do is to use the `--cache-dir=.turbo-cache` argument and then cache that directory separately.

**Reply by florianmatz** [reply]
Thanks for the reply. I know about the default location and the option to store the cache elsewhere. 

I‘m more after a working azure pipeline config or a kind of field report / best practice of how it is properly done.

**Reply by chuanqisun** [reply]
I have a similar question. On a high level, I believe a task like this could work: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache, and the closest example I can find is with yarn: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#configure-the-cache-task I'm curious if anyone has successfully wired it up.

**Comment by jonathanirvin-ast** [comment]
Same here. I'd love to know what key file I need to look at in order to determine when the cache should hit or miss.

**Comment by hlavacek** [comment]
This isn't yet perfect, but kind of working. The Cache@2 task is checking the cache key, if it doesn't change, then it doesn't update the cache - which doesn't play very well with the cache of turborepo being updated almost every build, as almost every build there is some change in that cache. What we have done is to force the Cache@2 task to almost always push new cache entries in after the build and also do the cleanup of the cache to avoid too large cache over time:
```
- task: Cache@2
  inputs:
    key: '"turbo" | "$(Agent.OS)" | "$(Build.SourceBranch)" | "$(Build.SourceVersion)"'
    # the keys are set up to first try the current branch or try to fetch main otherwise, to use main branch cache for feature branches
    restoreKeys: |
      "turbo" | "$(Agent.OS)" | "$(Build.SourceBranch)"
      "turbo" | "$(Agent.OS)" | "main"
      "turbo" | "$(Agent.OS)"
      "turbo"
    path: node_modules/.cache
# do the build tasks here
- task: Bash@3
  displayName: cache_cleanup
  inputs:
    targetType: inline
    failOnStderr: true
    # this finds the files in the cache older than 4 days and removes them
    script: |
      find node_modules/.cache/turbo -mtime +4 -type f -delete
```
