### DISCUSSION TITLE
Distributed task execution

### DISCUSSION THREAD

**Discussion by EWhite613** [vercel/turborepo#7766] [Ideas]
### Goals

1. Take a command like `turbo run test` and split
2. Be able to specify the amount of partitions `turbo run test --split=4`
3. Be able to specify which partition you wish to run `turbo run test --split=4 --partition=1` (or multiple `turbo run test --split=4 --partition=1`)

### Non-goals

1. A balancing of the partitions

### Background

I would like to be able to take a command like `turbo run test` and distribute it across multiple agents. In order to increase parallelization in my builds and overall build time to complete.

I see @sppatel has made an article on doing this https://medium.com/@sppatel/maximizing-job-parallelization-in-ci-workflows-with-jest-and-turborepo-da86b9be0ee6 but I wonder if there could be an official implementation in here.

The alternative here would be for developers to maintain they're own script or build a third party package to help consolidate effort.

### Proposal

I think using @sppatel article we could build it and just need to describe the interface such as `split` (for how many shards) and `partition` to specify which ones you wish to execute. We have the graph so I think it's feasible to do this.

I think people may want is the balancing, which could definitely be done as an enhancement. Perhaps providing an option to be explicit about which packages are in your shards would work.

**Comment by EWhite613** [comment]
I assume this has been discussed before, but I couldn't find it in my search. So I thought I would make a discussion to track this.

**Comment by dante01yoon** [comment]
Do we have further discussion about this topic? or any enhancements on Distributed task execution?

**Comment by geekyarjun** [comment]
Hi, any update on this?

**Comment by moltar** [comment]
I came here with the same idea.

My goal was to be able to shard the tasks in a GitHub Actions matrix.

I accept that there will be some overlap, and double builds of some essential root packages. But I want Turborepo to compute this graph most optimally, and even suggest the total shard count. I think it can just return groups with packages in them, as these can be fed directly to the GitHub matrix then and be used in the filter clause.

So turbo needs to basically compute the most optimal build graph within some range of shards (matrix) given by the user, e.g. `--min=2 --max=10` (have a minimum of 2 shards, and no more than 10) and then turbo will compute the layout of the shards based on the dependency graph.

**Comment by elpddev** [comment]
Also looking into this. 

NX has this kind of functionality in [NX Distribute Task Execution (Nx Agents)](https://nx.dev/docs/features/ci-features/distribute-task-execution)

**Comment by elpddev** [comment]
I finally wrote a small facility to help me with this. Dog fooding it on my own monorepo and so far it works. 
https://dxcore.dev/

I wrapped it up as a SAAS service. 

It can be used in github actions with matrix and a dispatcher job. 

Currently it is in beta and free for that duration. Or it can be self hosted/used with some tweaking on GitHub actions only using the OSS version. 

```yml
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: join-with/dxcore-dispatch-action@v1
        with:
          coordinator-url: https://dxcore.dev
          token: ${{ secrets.DXCORE_TOKEN }}
          command: turbo run lint test build --dry=json
      - if: always()
        uses: join-with/dxcore-finish-action@v1
        with:
          coordinator-url: https://dxcore.dev
          token: ${{ secrets.DXCORE_TOKEN }}

  agents:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4
      - uses: join-with/dxcore-agent-action@v1
        with:
          coordinator-url: https://dxcore.dev
          token: ${{ secrets.DXCORE_TOKEN }}
```
