### DISCUSSION TITLE
How can I specify which url Playwright will run the tests on CI?

### DISCUSSION THREAD

**Discussion by lucasfelixs** [vercel/turborepo#8000] [Help]
### Summary

To contextualize, I have a turborepo project that there are two apps, preview deployments are made in all prs of these two projects, and I want to run the e2e tests with playwright pointing to the preview deploy url. I already did this flow in other project that is not a turborepo, is just a normal next project, and it works perfectly. I want to do the same thing but now in the turborepo project, running the tests of all apps, but I don't know how to specify which url the tests will run on.

For example, in the normal next project that I already did, I specify the url passing `${{ github.event.deployment_status.target_url }}`, but how it will works if I have two preview deployments in PR? I was thinking to create two ci configuration to both projects appoint to each `deployment_status.target_url` but I don't know how to access each deployment_url.

This is the .yaml configuration to run e2e tests in the another project, I would like to do the same thing in the turborepo project:

```yaml
name: Playwright E2E tests

on:
  deployment_status:
jobs:
  test-e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
        CI: true
      run: pnpm exec playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    
    - name: Upload blob report to GitHub Actions Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: blob-report
        retention-days: 1
```
