### DISCUSSION TITLE
CI / Github Actions: use of --since (only run on affected packages)

### DISCUSSION THREAD

**Discussion by graup** [vercel/turborepo#805] [Help] [answered]
I tried using `--since` in my Github Action and noticed it does not work when doing a shallow fetch due to the use of `...` in the [diff command](https://github.com/vercel/turborepo/blob/c9f7264d494b8cfc1c9f1f2c0762e2a2175b725c/cli/internal/scm/git.go#L77).

It works with `fetch-depth: 0`:

```
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --prefer-offline --frozen-lockfile
      - run: yarn turbo run test --since=origin/$GITHUB_BASE_REF
 ```

Obviously we need to fetch the base branch, but for a simple diff just shallow-fetching both the ref and the base ref should be enough. It doesn't work because `git diff base...HEAD` needs the complete history. Why can't we do `git diff base..HEAD`? Is there a way this can be improved?

If not, let's add a note to the [documentation](https://turborepo.org/docs/reference/command-line-reference#--since).

Also, it would be nice if the git error would be shown instead of just "error 128" ([here](https://github.com/vercel/turborepo/blob/c9f7264d494b8cfc1c9f1f2c0762e2a2175b725c/cli/internal/scm/git.go#L80)).
