### DISCUSSION TITLE
CI: turbo cache between Gitlab jobs

### DISCUSSION THREAD

**Discussion by thomasneger** [vercel/turborepo#8053] [Help]
### Summary

Hi! I have been trying to setup my Gitlab CI to to properly cache and reuse the turbo cache in between jobs.

I have split my CI workflow into 2 stages:

1. `test` stage - runs only when a dev pushes a new branch. It will check typescript, run the tests and eslint
2. `build` stage - runs after merge on main branch

This setup has worked well for my team, as we use it in combination of [GitLab fast-forward merge method](https://docs.gitlab.com/ee/user/project/merge_requests/methods/#fast-forward-merge), so that developers have to pass the typescript build, tests and eslint against the latest main before merging.

Here is a reduced version of my `.gitlab-ci.yml` file:

```yaml
image: node:20

stages:
  - test
  - build

.prepare_pnpm:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install --prefer-offline --ignore-scripts

test:
  stage: test
  extends:
    - .prepare_pnpm
  script:
    - pnpm run build:check
    - pnpm run test
    - pnpm run lint
  cache:
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm-store
      # This creates a unique cache key for each branch or tag
    - key: cache-$CI_COMMIT_REF_SLUG
      # If a branch-specific cache is not found (for example, if the job is running on a new branch),
      # it will fall back to the cache from the default branch.
      # This is useful because the default branch's cache is likely to be the most up-to-date and relevant
      fallback_keys:
        - cache-$CI_DEFAULT_BRANCH
      # This is where Turbo stores its cache
      # Caching this directory should help speed up Turbo's operations by reusing previous results where possible
      paths:
        - node_modules/.cache/turbo
  rules:
    # Only on feature branches
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != 'merge_request_event'

build:
  stage: build
  extends:
    - .prepare_pnpm
  script:
    - pnpm run build --filter=@acme/storybook --filter=web
  cache:
    - key:
        files:
          - pnpm-lock.yaml
      paths:
        - .pnpm-store
      # This creates a cache for the default "main" branch
    - key: cache-$CI_DEFAULT_BRANCH
      # This is where Turbo stores its cache
      paths:
        - node_modules/.cache/turbo
  artifacts:
    paths:
      - apps/storybook/storybook-static
      - apps/web/dist
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG'
      when: always
```

I think that with this setup, the `build` stage will benefit from the previously cached turbo run ✅.

However, the `test` stage will never be able to use the fallback key `cache-$CI_DEFAULT_BRANCH` ❌ as that job never runs on main (by design).

So far, the only solutions I have found would be to either let the `test` job run on `main`, or merge both `build` and `test` into a single job that would run on every branch. But that defeats the entire purpose of the original optimization.

Opinions on how I could fix that?

Thank you very much for the support.
