### DISCUSSION TITLE
How can turbo build read variables added in a Azure Devops Variable Group?

### DISCUSSION THREAD

**Discussion by simpel** [vercel/turborepo#8707] [Help] [answered]
### Summary

Hi all! 

We're creating a Azure DevOps pipeline and have a variable group with a bunch of vars. When running the pipeline we can see that the vars are available when running. But Turborepo is not picking them up for some reason! Is it not enough to do this?

Here borht TESTVAR and VARIABLEGROUPVAR prints out fine but when running pnpm build the build commands in the monorepo cant read them....

```
  - task: CmdLine@2
    displayName: "🏗️ Building monorepo"
    continueOnError: false
    inputs:
      script: |
        echo "The value of TESTVAR is: $TESTVAR"
        echo "The value of VARIABLEGROUPVAR is: $VARIABLEGROUPVAR"
        pnpm build
    env:
      TESTVAR: "TESTVAR ROCKS"
```
