### DISCUSSION TITLE
NextJS Turbo monorepo deployment issue on AWS Amplify

### DISCUSSION THREAD

**Discussion by haroonrashid2210** [vercel/turborepo#9136] [Help]
### Summary

I am deploying nextjs turbo mono repo on AWS Amplify. AWS Amplify is not giving me any errors but it is neither showing anything. Instead, it is showing "Internal Server Error".

While creating the project, I check marked that my project is a monorepo but currently I am only deploying the client app.

I have deployed to the vercel but that is working fine. On vercel I created 2 projects and deployed admin and client separately. I only configured build command and vercel managed everything else.

These are vercel build commands for both apps

```
cd ../.. && npx turbo run build --filter=client
cd ../.. && npx turbo run build --filter=admin
```

amplify.yml
```
version: 1
applications:
  - appRoot: apps/client
    frontend:
      phases:
        preBuild:
          commands:
            - cd apps/client
            - npm i pnpm --global
            - npx pnpm install
        build:
          commands:
            - cd ../.. && npx turbo run build --filter=client
      artifacts:
        baseDirectory: apps/client/.next
        files:
          - '**/*'
      cache:
        paths:
          - .next/cache/**/*
          - .npm/**/*
      buildPath: /

```

Environment Variables
```
All branches    AMPLIFY_DIFF_DEPLOY         false
All branches    AMPLIFY_MONOREPO_APP_ROOT   apps/client
```

I tried deploying options (i.e. marking the project as a mono repo and unmarking project as monorepo). But no solutions worked.

Folder Structure
![image](https://github.com/user-attachments/assets/57512caf-7056-4cd1-aa45-c3aaff5d14ed)

**Comment by vuvanthuan** [comment]
I trouble in it, too. Have you solved that issue yet?

**Comment by haroonrashid2210** [comment]
I resolved the issue by adding a `.npmrc` file as required by the [[AWS documentation](https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html#turborepo-pnpm-monorepo-configuration)]. Here's the configuration I used for `.npmrc`:

```
node-linker=hoisted
strict-peer-dependencies=false
auto-install-peers=true
shamefully-hoist=true
```

Additionally, I made adjustments to my `amplify.yml` file, which might differ depending on your project setup. Here's the configuration:

```yaml
version: 1
applications:
  - appRoot: apps/admin
    frontend:
      buildPath: '/'
      phases:
        preBuild:
          commands:
            - npm install -g pnpm
            - pnpm install
        build:
          commands:
            - pnpm build:admin
            - echo "YOUR_ENV_VARIABLE=$YOUR_ENV_VARIABLE" >> apps/admin/.env
      artifacts:
        baseDirectory: apps/admin/.next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - apps/admin/node_modules/**/*
          - apps/admin/.next/cache/**/*
```

package.json > script
```
"build:admin": "turbo run build --filter=admin"
```

**Reply by omarbakr2020** [reply]
I still get the same error, even after adding the .npmrc. it worked for just one deployment, but once I merged my PRs, it got corrupted again, and dynamic routes no longer work. Is there another workaround for this?

AGAIN: the build is successful, but dynamic routes are not working (500 internal server error)
 
 @haroonrashid2210 
 
```
version: 1
applications:
  - frontend:
      buildPath: /
      phases:
        preBuild:
          commands:
            - npm install -g pnpm
            - pnpm install
        build:
          commands:
            - echo "__NEXT_PRIVATE_PREBUNDLED_REACT=next" >> apps/web/.env
            - env | grep -e NEXT_PUBLIC_ >> apps/web/.env
            - cat apps/web/.env
            - pnpm run build:web
      artifacts:
        baseDirectory: apps/web/.next
        files:
          - '**/*'
      cache:
        paths:
          # - .next/cache/**/*
          # - .npm/**/*
          - node_modules/**/*
          - apps/web/node_modules/**/*
          - apps/web/.next/cache/**/*
    appRoot: apps/web

  - frontend:
      buildPath: /
      phases:
        preBuild:
          commands:
            - npm install -g pnpm
            - pnpm install
        build:
          commands:
            - echo "__NEXT_PRIVATE_PREBUNDLED_REACT=next" >> apps/admin/.env
            - env | grep -e NEXT_PUBLIC_ >> apps/admin/.env
            - cat apps/admin/.env
            - pnpm run build:admin
      artifacts:
        baseDirectory: apps/admin/.next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - apps/admin/node_modules/**/*
          - apps/admin/.next/cache/**/*
    appRoot: apps/admin

```
