### DISCUSSION TITLE
Remote cache hits between github actions envs and .env.local envs

### DISCUSSION THREAD

**Discussion by agualis** [vercel/turborepo#9768] [Help] [answered]
### Summary

In `turbo.json` I have a build task that has `.env.local` inside `inputs` option (as [recommended in the official turbo docs](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#handling-env-files)).

```json
  "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env.local"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
```

in the same `turbo.json` I have some global env vars that are used in the build process: 

```
  "globalEnv": [
    "FOO",
    "BAR",
```
]

My `checks.yml` in github actions uses those envs: 

```yaml
env:
  FOO:1
  BAR:2 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run build
        run: pnpm run build # Calls turbo build
```

If a user runs `turbo build` with this `.env.local` content: 

```
  FOO=1
  BAR=2 
```

The local build output and the CI build output  *should be equivalent*  but there will never be a cache hit cause **in CI `.env.local` won't be defined, so turbo `inputs` (and generated cache) will be always different** .

Is there a way to address that setup?

Thanks in advance!

#### Scenario 1

I have a turborepo with, for instance, a nextjs app and some packages.

I have a `github action` to: 
1. Run the `build` script
2. Run `e2e tests` pointing to that build

If a user locally runs a build with the same envs and pushes it to the remote cache, I would expect CI to get the build from the remote cache. 

#### Scenario 2

Vercel runs preview deployments in every PR but, even if using the same env values, it will never hit user cached builds due to the same reason above (users run builds with `.env.local` while vercel runs builds with plain system envs defined in the vercel console).
