### DISCUSSION TITLE
Turbo prune (2.2.3 to 2.4.2) does not prune custom turbo.json in scope packages

### DISCUSSION THREAD

**Discussion by iki** [vercel/turborepo#9974] [Help]
### Summary

In monorepo root I have task `generate` that lets each package specify dependencies in its own `turbo.json`, because it works differently for `api` (node+apollo) and `app` (next.js) packages:

```yaml
  "generate": {
      "dependsOn": ["^build"]
      // --- Let each package to specify its inputs and outputs ---
    },
```

Additionally, our `app` `generate` task depends on `api` `generate` task, like specified in `app/turbo.json`:

```yaml
    "generate": {
      "dependsOn": ["@acme/xx-api#generate"],
      "inputs": ["../api/generated/schema.graphql", "graphql/**/*.graphql"],
      "outputs": ["generated/**"]
    },
```

⚠️ The issue is that when pruning `app`, the `app/turbo.json` is not pruned correctly and still contains that dependency.

```sh
pnpm turbo prune --scope=@acme/xx-app --out-dir=build/@acme/xx-app --docker
```

Is there any option to remove the dependencies to monorepo packages that are not part of the pruned tree?

cc @chris-olszewski
