### ISSUE TITLE
Support for build matrix in continuous integration

### ISSUE THREAD

**Issue by fubhy** [vercel/turborepo#501]
### Describe the feature you'd like to request

It would be great if turborepo had the ability to parallelize tasks of disconnected groups in the dependency graph via a build matrix.

### Describe the solution you'd like

Imagine you have a monorepo in which the `build` script for each package can run in isolation and there are no dependencies (or if there are, the dependency graph for these packages results in a certain number of disconnected groups), e.g.:

- package 1,
- package 2, 3, 5
- package 4,
- package 5, 6

Since turborepo knows about the relationship between all packages (dependencies and dependents), if I was to configure e.g. my github workflow to run as a matrix (simply for the purpose of parallelization, no difference in environments), it would be great if there was a way for me to tell turborepo that it's running in a matrix and then have it (deterministically) split up the work between the individual runtimes.

### Describe alternatives you've considered

Nothing really :)

**Comment by jaredpalmer** [comment]
This should be possible with `--dry=json` now and a custom script.

**Comment by yacinehmito** [comment]
If this helps anyone, here's a script we've made to compute matrix parameters. This is really tailored to the way our CI works, so you might need adjustments.

We have one job per type of check, say: "format", "lint", "test" and "type-check".

Because test and type-check take a lot of time, we want to run those tasks in parallel in different jobs. We have defined the jobs "test-matrix" and "type-check-matrix" that do that. The jobs "test" and "type-check" depend on them respectively. They aggregate the output to give the final answer as whether the check passes. This is necessary to make the check required on a PR.

How to split into different parallel jobs is not decided by Turborepo but hardcoded in the script shared below (variable `jobDefinitions`). In our case, we have 2 big server applications defined as packages (we'll call them `@foo/service1` and `@foo/service2`), a big frontend application (calling it `@foo/webapp`), a design system (calling it `@foo/design-system`) and a lot of other small reusable packages.

We want to run in parallel:
- `service1` on its own
- `service2` on its own
- `webapp` with `design-system`
- all the other packages together

What the script does is leverage `turbo --affected` to determine which packages should be tested / type-checked, and then only run the sub-jobs of the matrix on affected packages.

We set `jobDefinitions` as follows:

```typescript
const jobDefinitions = {
  test: {
    service1: ["@foo/service1"],
    service2: ["@foo/service2"],
    frontend: ["@foo/webapp", "@foo/design-system"]
    // no need to define the rest, there will be an entry "remaining" with the packages not mentioned anobe
  },
  'type-check': {
    // identical, but you can define the groups differently if you want
    service1: ["@foo/service1"],
    service2: ["@foo/service2"],
    frontend: ["@foo/webapp", "@foo/design-system"]
  }
}
```

We've put the script (shared below) in `.github/scripts/compute_jobs_matrices.ts`.

There's a job called `compute-matrices` defined as follows in the GitHub Actions workflow:

```yaml
compute-matrices:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{ steps.compute-matrices.outputs.test-matrix }}
      type-check-matrix: ${{ steps.compute-matrices.outputs.type-check-matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute all matrices
        id: compute-matrices
        run: |
          node --experimental-strip-types ./.github/scripts/compute_jobs_matrices.ts > /tmp/matrices.json
          echo "All matrices:"
          cat /tmp/matrices.json

          TEST_MATRIX=$(cat /tmp/matrices.json | jq -c '.test // []')
          echo "test-matrix=$TEST_MATRIX" >> $GITHUB_OUTPUT

          TYPE_CHECK_MATRIX=$(cat /tmp/matrices.json | jq -c '."type-check" // []')
          echo "type-check-matrix=$TYPE_CHECK_MATRIX" >> $GITHUB_OUTPUT
```

For the jobs `test-matrix`, we do this:

```yaml
  test-matrix:
    name: test-matrix (${{ matrix.name }})
    needs: compute-matrices
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.compute-matrices.outputs.test-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests with filters
        run: |
          cmd="turbo test"
          packages='${{ toJson(matrix.packages) }}'
          for pkg in $(echo "$packages" | jq -r '.[]'); do
            cmd="$cmd --filter $pkg"
          done
          eval "$cmd"
```

Similar thing for `type-check-matrix`.

To gather the results of `test-matrix`, we define the following job:

```yaml
  test:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: test-matrix
    steps:
      - run: exit 1
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
```

Similar thing for `type-check`.

Here's the script below. You will need to put `jobsDefinitions` inside. FYI Claude Code did most of the work.

```typescript
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";


// PUT YOUR JOBS YOU WANT TO PARALLELIZE HERE, WITH THE GROUP OF PACKAGES FOR EACH.
// See the example in the explanation above.
const jobDefinitions = {} satisfies JobDefinitions;

interface TurboTask {
  taskId: string;
  task: string;
  package: string;
  directory: string;
}

interface TurboDryRunOutput {
  tasks?: TurboTask[];
}

interface PackageJson {
  scripts?: Record<string, string>;
}

/**
 * Identifies packages that would run for multiple tasks according to Turbo,
 * filtering out packages that don't actually have the tasks in their package.json files.
 *
 * @param taskNames - Array of task names to identify (e.g., ["test", "type-check"])
 * @returns A map of task names to arrays of package names that have the task
 * @throws Error if turbo command fails or package.json is missing
 */
export function identifyAffectedPackages(
  taskNames: string[],
): Record<string, string[]> {
  // Run turbo dry-run to get affected tasks for all requested tasks at once
  const result = spawnSync("turbo", [
    "--affected",
    "--dry-run=json",
    ...taskNames,
  ], {
    encoding: "utf8",
    maxBuffer: 10 * 1024 * 1024, // 10MB buffer
    stdio: ["ignore", "pipe", "pipe"],
  });

  if (result.error) {
    // Handle spawn errors (e.g., command not found)
    let errorMessage = `turbo command failed: ${result.error.message}`;

    if (result.error.code === "ENOENT") {
      errorMessage += "\nMake sure turbo is installed and available in PATH";
    } else if (result.error.code === "ENOBUFS") {
      errorMessage +=
        "\nOutput too large. Try running with fewer packages or increase buffer size.";
    }

    throw new Error(errorMessage);
  }

  if (result.status !== 0) {
    // Handle non-zero exit codes
    let errorMessage = `turbo command failed with exit code ${result.status}`;

    if (result.stderr) {
      const stderr = result.stderr.trim();
      // Check if stderr contains actual error messages (not just version info)
      if (stderr && !stderr.match(/^turbo \d+\.\d+\.\d+$/)) {
        errorMessage += `\nError output: ${stderr}`;
      }
    }

    if (result.stdout) {
      // Sometimes turbo puts error messages in stdout
      const stdout = result.stdout.trim();
      if (stdout && !stdout.startsWith("{")) {
        errorMessage += `\nOutput: ${stdout}`;
      }
    }

    // Common turbo error scenarios
    if (result.stderr && result.stderr.includes("not a git repository")) {
      errorMessage +=
        "\n\nHint: This command must be run inside a git repository";
    } else if (result.status === 2) {
      errorMessage +=
        "\n\nHint: Exit code 2 often means turbo encountered an error. Check that:";
      errorMessage += "\n  - You are in a git repository with commits";
      errorMessage += "\n  - The turbo.json file is valid";
      errorMessage += "\n  - The task names exist in turbo.json";
    }

    throw new Error(errorMessage);
  }

  const output = result.stdout;
  const dryRunData = JSON.parse(output) as TurboDryRunOutput;

  // Group tasks by task name
  const tasksByName: Record<string, TurboTask[]> = {};

  if (dryRunData.tasks) {
    for (const task of dryRunData.tasks) {
      if (!tasksByName[task.task]) {
        tasksByName[task.task] = [];
      }
      tasksByName[task.task].push(task);
    }
  }

  // Check if each task actually exists in the package.json
  const packagesByTask: Record<string, string[]> = {};

  for (const taskName of taskNames) {
    const tasksForThisName = tasksByName[taskName] || [];
    const existingPackages: string[] = [];

    for (const task of tasksForThisName) {
      const packageJsonPath = join(task.directory, "package.json");

      try {
        const packageJsonContent = readFileSync(packageJsonPath, "utf8");
        const packageJson = JSON.parse(packageJsonContent) as PackageJson;

        // Check if the task exists in the scripts section
        if (packageJson.scripts && packageJson.scripts[taskName]) {
          existingPackages.push(task.package);
        }
      } catch (error) {
        if (
          error instanceof Error && "code" in error && error.code === "ENOENT"
        ) {
          throw new Error(
            `Missing package.json at ${packageJsonPath} for package ${task.package}`,
          );
        }
        throw error;
      }
    }

    packagesByTask[taskName] = existingPackages;
  }

  return packagesByTask;
}

/**
 * Mapping of tasks to groups of packages that must have a dedicated job for
 * it. If a task is not listed, it means that all packages run it. If multiple
 * packages are listed together, it means that they will run in the same job
 * (if they do run at all).
 */
type JobDefinitions = Record<string, Record<string, string[]>>;

interface MatrixEntry {
  name: string;
  packages: string[];
}

/**
 * Computes job matrices for all tasks defined in jobDefinitions.
 * For each task, returns an array of matrix entries suitable for GitHub Actions.
 *
 * @param jobDefinitions - The job definitions mapping tasks to package groups
 * @param affectedPackagesByTask - A map of task names to affected packages for that task
 * @returns A record where keys are task names and values are arrays of matrix entries
 */
export function computeMatrices(
  jobDefinitions: JobDefinitions,
  affectedPackagesByTask: Record<string, string[]>,
): Record<string, MatrixEntry[]> {
  const result: Record<string, MatrixEntry[]> = {};

  // Process each task that has affected packages
  for (const [task, packages] of Object.entries(affectedPackagesByTask)) {
    const specificJobDefinitions = jobDefinitions[task];

    if (specificJobDefinitions === undefined) {
      throw new Error(`Unexpected job definition of 'undefined' for task: ${task}`);
    }

    const output: MatrixEntry[] = [];
    const remainingPackages = new Set(packages);

    // Process each named group of packages that should run together
    for (
      const [groupName, groupPackages] of Object.entries(specificJobDefinitions)
    ) {
      const matchingPackages = groupPackages.filter((pkg) =>
        remainingPackages.has(pkg)
      );
      if (matchingPackages.length > 0) {
        // Add the group as a matrix entry
        output.push({
          name: groupName,
          packages: matchingPackages,
        });
        // Remove matched packages from remaining
        matchingPackages.forEach((pkg) => remainingPackages.delete(pkg));
      }
    }

    // Add any remaining packages as a single group named "remaining"
    if (remainingPackages.size > 0) {
      output.push({
        name: "remaining",
        packages: Array.from(remainingPackages),
      });
    }

    result[task] = output;
  }

  return result;
}

function main(): void {
  try {
    // Get affected packages for all tasks defined in jobDefinitions at once
    let affectedPackagesByTask: Record<string, string[]> = {};

    try {
      // Call turbo once with all tasks for efficiency
      affectedPackagesByTask = identifyAffectedPackages(
        Object.keys(jobDefinitions),
      );

      // Filter out tasks with no affected packages
      affectedPackagesByTask = Object.fromEntries(
        Object.entries(affectedPackagesByTask).filter(([_, packages]) =>
          packages.length > 0
        ),
      );
    } catch (error) {
      // If turbo fails, log detailed error and exit
      console.error("\nError: Failed to get affected packages");

      const errorMessage = error instanceof Error
        ? error.message
        : String(error);
      console.error("Details:", errorMessage);

      // Provide helpful context
      if (errorMessage.includes("not a git repository")) {
        console.error(
          "\nHint: Make sure you are running this command from within a git repository",
        );
        console.error("      and that you have committed your initial files.");
      } else if (errorMessage.includes("ENOENT")) {
        console.error(
          "\nHint: Make sure turbo is installed. You can install it with:",
        );
        console.error("      npm install -g turbo");
        console.error("      or ensure it's available in your nix environment");
      }
      process.exit(1);
    }

    const matrices = computeMatrices(jobDefinitions, affectedPackagesByTask);

    console.log(JSON.stringify(matrices, null, 2));
  } catch (error) {
    if (error instanceof Error) {
      if (error.message.includes("No such file or directory")) {
        console.error(
          "Error: turbo command not found. Please ensure Turborepo is installed.",
        );
      } else if (error.message.includes("JSON")) {
        console.error("Error: Failed to parse turbo dry-run output as JSON.");
      } else if (error.message.includes("Missing package.json")) {
        console.error(error.message);
      } else {
        console.error("Error:", error.message);
      }
    } else {
      console.error("Error:", String(error));
    }
    process.exit(1);
  }
}

// Execute main only if the module is run directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
```
