### ISSUE TITLE
[turborepo] cypress/base:18.15.0 image always invalidates the remote turbo cache in ci for Integration Cypress Tests step

### ISSUE THREAD

**Issue by AnnaVih** [vercel/turborepo#5459]
### What version of Turborepo are you using?

1.9.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Remote turbo cache always gets invalidated when using cypress/base:18.15.0 image in ci for Integration Cypress Tests step.

### Expected Behavior

Instead of having all the time this - _**"cache miss, executing ###-###-###"**_ the expected behaviour will be having _**"cache hit, replaying output ###-###-###"**_

### To Reproduce

Use cypress/base:18.15.0 image in ci for running the Cypress Tests step. The step includes build script and then the run tests script.

```
- step: &e2e-cypress
        name: '💻 UI Integration Cypress Tests'
        image: cypress/base:18.15.0
        script:
          - yarn install --frozen-lockfile
          - yarn build --token=$TURBO_TOKEN
          - TURBO_TOKEN=$TURBO_TOKEN yarn cypress:ci:init
```
