### ISSUE TITLE
Return 0 exit code from 'turbo-ignore'

### ISSUE THREAD

**Issue by mehulkar** [vercel/turborepo#6348]
### Discussed in https://github.com/vercel/turbo/discussions/5647

<div type='discussions-op-text'>

<sup>Originally posted by **Tobjoern** July 31, 2023</sup>
From my current view, turbo-ignore returns the exit code '1' is a proejct changed, and '0' if it didn't.
Is there a specific reason behind this?

It leads to some very weird patterns, when integrating into a CI/CD system, epeciall with GH actions, since the immediately fail, whenvever a non-0 code is emitted.
But at the same time, I'm not very comfortable ignoring non-0 codes, since you never know, when something actually breaks.

![image](https://github.com/vercel/turbo/assets/31477665/40753255-9ecc-468c-982c-fa6335c2bf11)</div>

**Comment by tknickman** [comment]
This was done to support the ignored build step on Vercel ([docs](https://vercel.com/docs/projects/overview#ignored-build-step)):

> If the command exits with code 1, the build continues as normal
If the command exits with code 0, the build is immediately aborted, and the deployment state is set to CANCELED

**Comment by mehulkar** [comment]
@tknickman yeah agreed, but I think the ask to have an alternate behavior so it can be used in scripting is reasonable too. Although we might want to solve that some other way

**Comment by appleseed-iii** [comment]
plus 1

**Comment by baptisteArno** [comment]
Here is a full example of the workaround:

```yml
name: Deploy Partykit server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: oven-sh/setup-bun@v2
      - name: Run Turbo ignore
        id: check_changes
        run: |
          echo "Running script..."

          set +e
          bunx turbo-ignore @typebot.io/partykit -task=build exit_code=$?
          set -e

          echo "Exit code: $exit_code"

          if [ $exit_code -eq 0 ]; then
            echo "hasClientApiHostChanged=0" >> $GITHUB_OUTPUT
          else
            echo "hasClientApiHostChanged=1" >> $GITHUB_OUTPUT
          fi
      - run: bun install
        if: steps.check_changes.outputs.hasClientApiHostChanged == '1'
```
