### ISSUE TITLE
v1.1.4 breaks "npm install" in GitHub Actions

### ISSUE THREAD

**Issue by aaron5670** [vercel/turborepo#820]
### What version of Turborepo are you using?

v1.1.4

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

All my GitHub Actions with Turborepo breaks after updating Turborepo from v1.1.3 to 1.1.4.

This is my GitHub Actions file:
```yaml
name: 'Deploy Booking API'

env:
  HOST: ***
  PASSWORD: ***
  BRANCH: ***
  APPLICATION: ***
  CONFIG_FILE: ***

on:
  workflow_dispatch:
  push:
    branches: [ 'staging' ]
    paths:
      - 'apps/booking-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Lint check
        run: npm run lint --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Caprover
        run: npm install -g caprover
      - name: Deploy to Caprover
        run: caprover deploy -h $HOST -p $PASSWORD -b $BRANCH -a $APPLICATION -c $CONFIG_FILE
```

My root package.json file:

```json

{
  "name": "turborepo-app",
  "private": true,
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev --parallel --continue",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{js,jsx,md}\"",
    "prepare": "husky install"
  },
  "devDependencies": {
    "config": "*",
    "husky": "7.0.4",
    "prettier": "2.5.1",
    "turbo": "1.1.4"
  },
  "engines": {
    "npm": ">=7.0.0",
    "node": ">=14.0.0"
  },
  "packageManager": "npm@8.3.1"
}
```
And the GitHub Actions error logs:
```
Run npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated puppeteer@[10](https://github.com/aaron5670/TopVakantiehuizen-v2/runs/5412045279?check_suite_focus=true#step:4:10).4.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /home/runner/work/myrep-v2/TopVakantiehuizen-v2/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! [turbo] Failed to find package "turbo-linux-64" on the file system
npm ERR! 
npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
npm ERR! package.json feature is used by turbo to install the correct binary executable
npm ERR! for your current platform. This install script will now attempt to work around
npm ERR! this. If that fails, you need to remove the "--no-optional" flag to use turbo.
npm ERR! 
npm ERR! node:internal/modules/cjs/loader:933
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: Cannot find module 'turbo'
npm ERR! Require stack:
npm ERR! - /home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/node-platform.js
npm ERR! - /home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/install.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
npm ERR!     at downloadedBinPath (/home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/node-platform.js:56:44)
npm ERR!     at checkAndPreparePackage (/home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/install.js:286:15)
npm ERR!     at Object.<anonymous> (/home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/install.js:3[11](https://github.com/aaron5670/TopVakantiehuizen-v2/runs/5412045279?check_suite_focus=true#step:4:11):1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1103:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/aaron5670/TopVakantiehuizen-v2/runs/5412045279?check_suite_focus=true#step:4:12))
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/node-platform.js',
npm ERR!     '/home/runner/work/TopVakantiehuizen-v2/TopVakantiehuizen-v2/node_modules/turbo/install.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-03T[18](https://github.com/aaron5670/TopVakantiehuizen-v2/runs/5412045279?check_suite_focus=true#step:4:18)_43_59_[37](https://github.com/aaron5670/TopVakantiehuizen-v2/runs/5412045279?check_suite_focus=true#step:4:37)9Z-debug-0.log
Error: Process completed with exit code 1.
```

### Expected Behavior

The GitHub actions worked before the update. I downgraded Turborepo back to 1.1.3 and now it works like before.

### To Reproduce

I hope you can repoduce it with the above YAML and JSON files...
