### ISSUE TITLE
`turbo xxx yyy --affected` seems broken after updating to v2.1.3

### ISSUE THREAD

**Issue by castarco** [vercel/turborepo#9208]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

can't, privative repository

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Which canary version will you have in your reproduction?

v2.1.4-canary.0

### Describe the Bug

It's quite difficult to describe, what I can say is that it crashes with the following message (in a Github Actions pipeline that works perfectly well with v2.1.2).

The relevant details:
- it does not fail in PR pipeline executions
- it fails once it runs on `main` branch
- v2.1.2 works perfectly fine
- seems related to the `--affected` flag
- I took care of removing ALL the caches of Github Actions, just to ensure that this wasn't happening because of a corrupted cache file, or because any mismatch between caches of prior versions and the expectations of the current version.

```
Run pnpm turbo knip typecheck lint test --affected
  pnpm turbo knip typecheck lint test --affected
  shell: /usr/bin/bash -e {0}
  env:
    IMAGE_NAME: ghcr.io/meeting-doctors/microservices-chat
    BRANCH_NAME: main
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

Attention:
Turborepo now collects completely anonymous telemetry regarding usage.
This information is used to shape the Turborepo roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://turbo.build/repo/docs/telemetry

Resolved base ref from GitHub Actions event: 65f9edd184b41c883b7e891edee350f8f[2](https://github.com/Meeting-Doctors/microservices-chat/actions/runs/11140068122/job/30958426027#step:7:2)4eb4eb
  x Unable to query SCM: git error: fatal: bad object
  | 65f9edd184b41c88[3](https://github.com/Meeting-Doctors/microservices-chat/actions/runs/11140068122/job/30958426027#step:7:3)b7e891edee350f8f24eb4eb
  | 
  `-> git error: fatal: bad object 65f9edd18[4](https://github.com/Meeting-Doctors/microservices-chat/actions/runs/11140068122/job/30958426027#step:7:4)b41c883b7e891edee3[5](https://github.com/Meeting-Doctors/microservices-chat/actions/runs/11140068122/job/30958426027#step:7:5)0f8f24eb4eb
```

### Expected Behavior

It shouldn't crash.

### To Reproduce

I can share a partial version of the Github Actions definition:

```yaml
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

env:
  IMAGE_NAME: "${{ vars.DOCKER_REPOSITORY_URL }}/some-image-name"
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"

defaults:
  run:
    working-directory: .

jobs:
  checks:
    name: "Run Automated Checks"

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: ["22.9.0"]
        pnpm-version: ["9.11.0"]

    runs-on: "${{ matrix.os }}"

    steps:
      # Preparing repository
      - name: Checkout repository # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      # Preparing tools
      - name: Install PNPM # v3.0.0
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }} # v4.0.2
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Preparing dependenies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Preparing cache
      - name: "Prepare Turbo Local Cache"
        id: "cache-turbo"
        #     actions/cache@v4.0.2 (we use the hash for security reasons)
        uses: "actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9"
        with:
          path: |
            ./.turbo/cache
            ./pkgs/chat-ms/.tsbuildinfo
            ./pkgs/chat-ms/.turbo
          key: "cache-turbo-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.pnpm-version}}-${{ hashFiles('.turbo.json') }}-${{ hashFiles('package.json') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('pkgs/**/*') }}"
          restore-keys: |
            cache-turbo-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.pnpm-version}}-${{ hashFiles('.turbo.json') }}-${{ hashFiles('package.json') }}-${{ hashFiles('pnpm-lock.yaml') }}-
            cache-turbo-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.pnpm-version}}-${{ hashFiles('.turbo.json') }}-${{ hashFiles('package.json') }}-
            cache-turbo-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.pnpm-version}}-${{ hashFiles('.turbo.json') }}-
            cache-turbo-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.pnpm-version}}-
            cache-turbo-${{ matrix.os }}-${{ matrix.node-version }}-
            cache-turbo-${{ matrix.os }}-
            cache-turbo-

      # Running checks
      - name: Run Many Checks
        run: pnpm turbo knip typecheck lint test --affected
```
